spring:
  application:
    name: user-service

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  datasource:
    url: jdbc:mysql://223.130.162.28:30100/bookdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 4

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8088

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka

logging:
  file:
    path: /tmp/thyme/logs
